using System;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.UI;
namespace GhostRally {
 public sealed class RallySession:MonoBehaviour{
  enum Mode{Menu,Loading,Countdown,Race,Paused,Result}
  Catalog catalog;ProgressStore progress;RallyUI ui;MobileDriving input;RallyCamera chase;RallyVehicle vehicle;StageWorld world;GameObject garage,ghost;GhostReplay replay;ReplayData record;Mode mode;int selectedCar=10,selectedStage,segment,nextGate;float clock,countdown,sampleClock;bool newBest;Text hud,clockText;Vector3 previous;
  public void Initialize(){catalog=Catalog.Load();progress=ProgressStore.Load();selectedStage=Array.FindIndex(catalog.tracks,x=>x.routeIndex==16);ui=new GameObject("Rally UI").AddComponent<RallyUI>();input=gameObject.AddComponent<MobileDriving>();input.autoGas=PlayerPrefs.GetInt("autogas",0)==1;input.tilt=PlayerPrefs.GetInt("tilt",0)==1;Time.fixedDeltaTime=1f/120;Application.targetFrameRate=60;Screen.sleepTimeout=SleepTimeout.NeverSleep;SetupLighting();ApplyGraphics(PlayerPrefs.GetFloat("renderScale",.85f),PlayerPrefs.GetInt("msaa",2));ShowMenu();}
  void SetupLighting(){var camera=new GameObject("Main Camera",typeof(Camera),typeof(AudioListener));camera.tag="MainCamera";camera.GetComponent<Camera>().nearClipPlane=.12f;camera.GetComponent<Camera>().farClipPlane=1600;camera.GetComponent<Camera>().allowHDR=true;camera.GetComponent<Camera>().GetUniversalAdditionalCameraData().renderPostProcessing=true;chase=camera.AddComponent<RallyCamera>();
   var sun=new GameObject("Late afternoon sun").AddComponent<Light>();sun.type=LightType.Directional;sun.intensity=2.1f;sun.color=new Color(1,.88f,.71f);sun.shadows=LightShadows.Soft;sun.transform.rotation=Quaternion.Euler(24,-32,0);RenderSettings.ambientMode=AmbientMode.Trilight;RenderSettings.ambientSkyColor=new Color(.38f,.52f,.69f);RenderSettings.ambientEquatorColor=new Color(.3f,.35f,.4f);RenderSettings.ambientGroundColor=new Color(.13f,.12f,.1f);RenderSettings.fog=true;RenderSettings.fogMode=FogMode.Exponential;RenderSettings.fogColor=new Color(.58f,.66f,.7f);RenderSettings.fogDensity=.00065f;
   var volume=new GameObject("Mobile post processing").AddComponent<Volume>();volume.isGlobal=true;volume.profile=ScriptableObject.CreateInstance<VolumeProfile>();var tone=volume.profile.Add<Tonemapping>(true);tone.mode.value=TonemappingMode.ACES;var bloom=volume.profile.Add<Bloom>(true);bloom.intensity.value=.15f;bloom.threshold.value=1.2f;var vignette=volume.profile.Add<Vignette>(true);vignette.intensity.value=.14f;
  }
  void DestroyRace(){if(world!=null){world.gameObject.SetActive(false);Destroy(world.gameObject);}if(vehicle!=null){vehicle.gameObject.SetActive(false);Destroy(vehicle.gameObject);}if(ghost!=null)Destroy(ghost);vehicle=null;world=null;replay=null;input.active=false;input.Clear();chase.vehicle=null;}
  public void ShowMenu(){Time.timeScale=1;DestroyRace();mode=Mode.Menu;ui.Clear();if(garage!=null)Destroy(garage);garage=new GameObject("Showroom");var floor=GameObject.CreatePrimitive(PrimitiveType.Cylinder);floor.transform.SetParent(garage.transform,false);floor.transform.localScale=new Vector3(5,.1f,5);floor.transform.position=Vector3.down*.2f;floor.GetComponent<MeshRenderer>().sharedMaterial=new Material(Shader.Find("Universal Render Pipeline/Lit")){color=new Color(.06f,.09f,.1f)};
   var model=Resources.Load<GameObject>("Migration/Geometry/"+catalog.cars[selectedCar].id);if(model!=null)Instantiate(model,garage.transform);chase.transform.position=new Vector3(4.5f,2,-5.8f);chase.transform.LookAt(Vector3.up*.8f);
   ui.Label(ui.root,"GHOST RALLY",35,25,900,65,46);ui.Label(ui.root,"UNITY • ANDROID PREVIEW",38,92,650,35,18,ui.accent);
   var list=ui.ScrollList(38,150,370,390,catalog.tracks.Length);for(int i=0;i<catalog.tracks.Length;i++){int index=i;var stage=catalog.tracks[i];ui.Button(list,(i==selectedStage?"● ":"")+stage.name+(stage.wp>=0?" · WP "+(stage.wp+1):""),5,i*54,355,48,()=>{selectedStage=index;ShowMenu();},i==selectedStage);}
   var car=catalog.cars[selectedCar];ui.Label(ui.root,car.name,470,530,700,44,35);ui.Label(ui.root,$"{car.drive} · {car.power:0} PS · {car.mass:0} kg · {progress.rc} RC",470,576,690,35,23,ui.accent);
   ui.Button(ui.root,"‹",440,540,45,50,()=>{selectedCar=(selectedCar+catalog.cars.Length-1)%catalog.cars.Length;ShowMenu();});ui.Button(ui.root,"›",1190,540,45,50,()=>{selectedCar=(selectedCar+1)%catalog.cars.Length;ShowMenu();});
   ui.Button(ui.root,"EINSTELLUNGEN",38,575,370,52,ShowSettings);ui.Button(ui.root,"TUNING",470,631,230,55,ShowTuning);ui.Button(ui.root,"RENNEN STARTEN →",735,631,490,55,StartRace,true);ui.Button(ui.root,"LIZENZEN",38,639,370,48,ShowCredits);
  }
  void ShowCredits(){ui.Clear();ui.Panel(ui.root,80,40,1120,630);ui.Label(ui.root,"KARTEN, RESSOURCEN UND LIZENZEN",110,70,1060,45,30);var scroll=ui.ScrollList(110,135,1060,435,1);scroll.sizeDelta=new Vector2(1060,3000);ui.Label(scroll,Resources.Load<TextAsset>("Migration/CREDITS").text,10,10,1015,2900,18);ui.Button(ui.root,"ZURÜCK",870,595,260,55,ShowMenu,true);}
  void ShowTuning(){ui.Clear();var car=catalog.cars[selectedCar];var u=progress.Upgrade(car.id);ui.Panel(ui.root,310,100,660,520);ui.Label(ui.root,car.name+" · TUNING",340,130,600,50,32);if(car.voc)ui.Label(ui.root,"VOC: Serienleistung bleibt gesperrt.\nKeine Leistungs-Upgrades verfügbar.",340,215,580,110,25);else{string[] keys={"MOTOR","FAHRWERK","BREMSEN"};int[] levels={u.engine,u.handling,u.brakes};for(int i=0;i<3;i++){int slot=i;int cost=150*(levels[i]+1);ui.Button(ui.root,$"{keys[i]} {levels[i]}/3 · {cost} RC",340,215+i*70,580,55,()=>{int level=slot==0?u.engine:slot==1?u.handling:u.brakes;int price=150*(level+1);if(level>=3||progress.rc<price)return;progress.rc-=price;if(slot==0)u.engine++;else if(slot==1)u.handling++;else u.brakes++;progress.Save();ShowTuning();});}}ui.Button(ui.root,"ZURÜCK",340,530,580,55,ShowMenu,true);}
  void ShowSettings(){bool paused=mode==Mode.Paused;ui.Clear();ui.Panel(ui.root,280,60,720,600);ui.Label(ui.root,"FAHREN UND GRAFIK",315,90,640,50,34);
   ui.Button(ui.root,"LENKUNG: "+(input.tilt?"NEIGEN":"DAUMEN"),315,165,650,50,()=>{input.tilt=!input.tilt;PlayerPrefs.SetInt("tilt",input.tilt?1:0);ShowSettings();});ui.Button(ui.root,"NEIGUNG KALIBRIEREN",315,225,650,50,input.Calibrate);ui.Button(ui.root,"AUTO-GAS: "+(input.autoGas?"AN":"AUS"),315,285,650,50,()=>{input.autoGas=!input.autoGas;PlayerPrefs.SetInt("autogas",input.autoGas?1:0);ShowSettings();});
   ui.Button(ui.root,"GRAFIK: FLÜSSIG",315,355,310,50,()=>ApplyGraphics(.7f,0));ui.Button(ui.root,"GRAFIK: DETAIL",655,355,310,50,()=>ApplyGraphics(1,4));ui.Label(ui.root,"Gamepad: Stick · RT Gas · LT Bremse · A Handbremse\nStart Pause · Y Kamera\nTouch rechts: nach oben Gas, nach unten Bremse.",315,425,640,85,23);ui.Button(ui.root,"FERTIG",315,560,650,55,()=>{PlayerPrefs.Save();if(paused)ShowPause();else ShowMenu();},true);
  }
  void ApplyGraphics(float scale,int aa){if(GraphicsSettings.currentRenderPipeline is UniversalRenderPipelineAsset p){p.renderScale=scale;p.msaaSampleCount=aa==0?1:aa;p.shadowDistance=aa==0?40:85;}PlayerPrefs.SetFloat("renderScale",scale);PlayerPrefs.SetInt("msaa",aa);}
  public void StartRace(){Time.timeScale=1;DestroyRace();if(garage!=null)Destroy(garage);mode=Mode.Loading;ui.Clear();var stage=catalog.tracks[selectedStage];var spec=catalog.cars[selectedCar];
   var go=new GameObject(spec.name);go.layer=8;var visual=Instantiate(Resources.Load<GameObject>("Migration/Geometry/"+spec.id),go.transform);foreach(Transform t in visual.GetComponentsInChildren<Transform>())t.gameObject.layer=8;
   var collider=go.AddComponent<BoxCollider>();collider.center=new Vector3(0,.82f,0);collider.size=new Vector3(1.65f,1.1f,spec.id=="lovo940voc"?4.6f:4.1f);go.AddComponent<Rigidbody>();vehicle=go.AddComponent<RallyVehicle>();FindWheels(visual.transform,vehicle);var config=JsonUtility.FromJson<VehicleCalibration>(Resources.Load<TextAsset>("Migration/Calibration/"+spec.id).text);var upgrade=progress.Upgrade(spec.id);if(!spec.voc){foreach(var point in config.torque)point.torque*=1+.05f*upgrade.engine;config.spring*=1+.06f*upgrade.handling;config.damper*=1+.06f*upgrade.handling;}vehicle.Configure(spec,config);vehicle.brakeScale=spec.voc?1:1+.1f*upgrade.brakes;vehicle.Body.isKinematic=true;
   var worldGo=new GameObject(stage.name);world=worldGo.AddComponent<StageWorld>();world.Build(stage,go.transform);vehicle.ResetTo(world.At(4)+Vector3.up*.08f,world.Heading(4));chase.vehicle=vehicle;input.vehicle=vehicle;input.active=false;input.Clear();input.autoGas=PlayerPrefs.GetInt("autogas",0)==1;input.tilt=PlayerPrefs.GetInt("tilt",0)==1;go.AddComponent<RallyAudio>().vehicle=vehicle;
   record=new ReplayData{stage=stage.id,car=spec.id};var prior=GhostReplay.Load(stage.id,spec.id);if(prior!=null){ghost=Instantiate(Resources.Load<GameObject>("Migration/Geometry/"+spec.id));foreach(var r in ghost.GetComponentsInChildren<Renderer>())foreach(var mat in r.materials){mat.SetColor("_BaseColor",new Color(.12f,.65f,.76f,.65f));}replay=ghost.AddComponent<GhostReplay>();replay.Configure(prior,ghost.transform);}
   clock=sampleClock=0;countdown=3;segment=0;nextGate=1;previous=vehicle.transform.position;mode=Mode.Countdown;DrawRace();
  }
  static void FindWheels(Transform visual,RallyVehicle car){string[] names={"wheel_fl","wheel_fr","wheel_rl","wheel_rr"};foreach(var t in visual.GetComponentsInChildren<Transform>())for(int i=0;i<4;i++)if(t.name==names[i])car.wheelVisuals[i]=t;
   // Procedural Godot cars use native WheelPivot names; exact names exported in the manifest.
   if(car.wheelVisuals[0]==null){var candidates=new System.Collections.Generic.List<Transform>();foreach(var t in visual.GetComponentsInChildren<Transform>())if(t.name.StartsWith("WheelPivot",StringComparison.Ordinal))candidates.Add(t);if(candidates.Count==4)for(int i=0;i<4;i++)car.wheelVisuals[i]=candidates[i];}
  }
  void DrawRace(){ui.Clear();var mapPanel=ui.Panel(ui.root,35,135,260,195);var mapRect=ui.Rect("Route",mapPanel,130,97.5f,260,195);mapRect.pivot=new Vector2(.5f,.5f);var map=mapRect.gameObject.AddComponent<RallyMap>();map.raycastTarget=false;map.Configure(world.stage,vehicle.transform);hud=ui.Label(ui.root,"",35,25,600,85,30);clockText=ui.Label(ui.root,"",520,25,310,65,38);ui.Button(ui.root,"PAUSE",1100,25,145,55,Pause);ui.Button(ui.root,"KAMERA",1100,95,145,50,()=>chase.cockpit=!chase.cockpit);ui.Button(ui.root,"ZURÜCKSETZEN",1030,155,215,50,Recover);ui.Label(ui.root,"DAUMEN ↔",45,570,280,100,28);ui.Label(ui.root,"GAS ↑\nBREMSE ↓",980,550,270,145,27,ui.accent);ui.Label(ui.root,"HANDBREMSE",945,440,285,60,25,ui.accent);}
  void Pause(){if(mode!=Mode.Race&&mode!=Mode.Countdown)return;mode=Mode.Paused;Time.timeScale=0;input.active=false;input.Clear();ShowPause();}
  void ShowPause(){ui.Clear();ui.Panel(ui.root,400,160,480,410);ui.Label(ui.root,"PAUSE",435,190,400,50,38);ui.Button(ui.root,"WEITER",435,265,410,55,()=>{Time.timeScale=1;mode=countdown>0?Mode.Countdown:Mode.Race;input.Clear();input.active=mode==Mode.Race;DrawRace();},true);ui.Button(ui.root,"EINSTELLUNGEN",435,335,410,55,ShowSettings);ui.Button(ui.root,"NEUSTART",435,405,410,55,StartRace);ui.Button(ui.root,"HAUPTMENÜ",435,475,410,55,ShowMenu);}
  void Recover(){if(world==null||vehicle==null)return;float d=Mathf.Max(4,Mathf.Min(Mathf.Min(world.stage.length-10,nextGate*200-10),segment*5));vehicle.ResetTo(world.At(d)+Vector3.up*.12f,world.Heading(d));input.Clear();previous=vehicle.transform.position;}
  void Update(){if((Keyboard.current!=null&&Keyboard.current.escapeKey.wasPressedThisFrame)||(Gamepad.current!=null&&Gamepad.current.startButton.wasPressedThisFrame))Pause();if(Gamepad.current!=null&&Gamepad.current.buttonNorth.wasPressedThisFrame)chase.cockpit=!chase.cockpit;
   if(mode==Mode.Countdown){countdown-=Time.deltaTime;clockText.text=countdown>0?Mathf.CeilToInt(countdown).ToString():"GO!";if(countdown<=0){mode=Mode.Race;vehicle.Body.isKinematic=false;input.active=true;}return;}if(mode!=Mode.Race)return;
   clock+=Time.deltaTime;sampleClock+=Time.deltaTime;segment=world.NearestSegment(vehicle.transform.position,segment);float progressMetres=world.stage.samples[segment].distance;hud.text=$"{vehicle.Speed*3.6f:000} KM/H   G{vehicle.Gear}\n{progressMetres/1000:0.0} / {world.stage.length/1000:0.0} KM";clockText.text=FormatTime(clock);
   if(sampleClock>=.05f){sampleClock%=.05f;record.frames.Add(new ReplayFrame{time=clock,position=vehicle.transform.position,rotation=vehicle.transform.rotation});}if(replay!=null)replay.Seek(clock);
   float gate=Mathf.Min(nextGate*200,world.stage.length-5);Vector3 at=world.At(gate),normal=world.Heading(gate)*Vector3.forward;float before=Vector3.Dot(previous-at,normal),after=Vector3.Dot(vehicle.transform.position-at,normal);
   if(before<0&&after>=0){Vector3 crossing=Vector3.Lerp(previous,vehicle.transform.position,Mathf.InverseLerp(before,after,0));if(Vector3.Distance(crossing,at)<Mathf.Max(5,world.stage.samples[segment].width*.5f+2)){if(gate>=world.stage.length-5){Finish();return;}nextGate++;}}
   previous=vehicle.transform.position;
  }
  void Finish(){mode=Mode.Result;input.active=false;input.Clear();vehicle.Body.isKinematic=true;record.duration=clock;newBest=progress.Finish(world.stage.id+"_"+vehicle.spec.id+"_unity1",clock);if(newBest)GhostReplay.Save(record);ui.Clear();ui.Panel(ui.root,320,130,640,460);ui.Label(ui.root,newBest?"NEUE BESTZEIT":"WP ABGESCHLOSSEN",360,170,560,50,34,ui.accent);ui.Label(ui.root,FormatTime(clock),360,235,560,75,60);ui.Label(ui.root,$"+{(newBest?120:80)} RC · {progress.rc} RC",360,335,560,50,28);ui.Button(ui.root,"NOCHMAL",360,415,250,60,StartRace,true);ui.Button(ui.root,"MENÜ",650,415,250,60,ShowMenu);var s=catalog.tracks[selectedStage];if(s.wp>=0&&s.wp<2)ui.Button(ui.root,"NÄCHSTE WP →",360,495,540,55,()=>{selectedStage=Array.FindIndex(catalog.tracks,x=>x.routeIndex==3&&x.wp==s.wp+1);StartRace();});}
  static string FormatTime(float time)=>$"{(int)time/60:00}:{time%60:00.000}";
  void OnApplicationPause(bool paused){if(paused)Pause();}void OnApplicationFocus(bool focused){if(!focused)Pause();}void OnDestroy(){Time.timeScale=1;}
 }
}
